In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1114, 3136, 6143, 5211],
 [1114, 3136, 6143, 1652],
 [1114, 2724, 6143, 4559],
 [2563, 8446, 8550, 1672, 3633],
 [2563, 8446, 8550, 1672, 6909],
 [7388, 1114, 3847, 6143, 373],
 [1348, 6184, 1003, 1672]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1114 3136 6143 5211]
 [   0    0    0    0 1114 3136 6143 1652]
 [   0    0    0    0 1114 2724 6143 4559]
 [   0    0    0 2563 8446 8550 1672 3633]
 [   0    0    0 2563 8446 8550 1672 6909]
 [   0    0    0 7388 1114 3847 6143  373]
 [   0    0    0    0 1348 6184 1003 1672]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 417ms/step


array([[[ 2.98337452e-02, -4.73856218e-02, -1.42607689e-02,
          2.37377994e-02,  5.35394996e-03, -2.97291521e-02,
          4.61648442e-02, -1.94370747e-03, -5.95600531e-03,
         -3.85981314e-02],
        [ 2.98337452e-02, -4.73856218e-02, -1.42607689e-02,
          2.37377994e-02,  5.35394996e-03, -2.97291521e-02,
          4.61648442e-02, -1.94370747e-03, -5.95600531e-03,
         -3.85981314e-02],
        [ 2.98337452e-02, -4.73856218e-02, -1.42607689e-02,
          2.37377994e-02,  5.35394996e-03, -2.97291521e-02,
          4.61648442e-02, -1.94370747e-03, -5.95600531e-03,
         -3.85981314e-02],
        [ 2.98337452e-02, -4.73856218e-02, -1.42607689e-02,
          2.37377994e-02,  5.35394996e-03, -2.97291521e-02,
          4.61648442e-02, -1.94370747e-03, -5.95600531e-03,
         -3.85981314e-02],
        [ 4.08550985e-02,  4.52124737e-02,  2.81438567e-02,
          2.90158056e-02, -3.58495861e-03,  2.57493891e-02,
          4.07189466e-02,  4.93762232e-02,  4.956590

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1114, 3136, 6143, 5211])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 200ms/step


array([[ 2.9833745e-02, -4.7385622e-02, -1.4260769e-02,  2.3737799e-02,
         5.3539500e-03, -2.9729152e-02,  4.6164844e-02, -1.9437075e-03,
        -5.9560053e-03, -3.8598131e-02],
       [ 2.9833745e-02, -4.7385622e-02, -1.4260769e-02,  2.3737799e-02,
         5.3539500e-03, -2.9729152e-02,  4.6164844e-02, -1.9437075e-03,
        -5.9560053e-03, -3.8598131e-02],
       [ 2.9833745e-02, -4.7385622e-02, -1.4260769e-02,  2.3737799e-02,
         5.3539500e-03, -2.9729152e-02,  4.6164844e-02, -1.9437075e-03,
        -5.9560053e-03, -3.8598131e-02],
       [ 2.9833745e-02, -4.7385622e-02, -1.4260769e-02,  2.3737799e-02,
         5.3539500e-03, -2.9729152e-02,  4.6164844e-02, -1.9437075e-03,
        -5.9560053e-03, -3.8598131e-02],
       [ 4.0855099e-02,  4.5212474e-02,  2.8143857e-02,  2.9015806e-02,
        -3.5849586e-03,  2.5749389e-02,  4.0718947e-02,  4.9376223e-02,
         4.9565900e-02,  9.9036805e-03],
       [-2.8179182e-02, -3.6428440e-02, -1.7080806e-02,  2.7672973e-02,
   